# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the local code to the container
COPY . .

# Install dependencies
RUN pip install .

# Command to run the MCP server
CMD ["uv", "--directory", "/path/to/index_directory", "run", "jewish_library"]
